[package]
name = "nessie"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indoc = "1.0"
clap = { version = "3.1.6", features = ["derive"] }
vec1 = "1.8.0"
